---
- name: Download NVM install script
  get_url:
    url: "https://raw.githubusercontent.com/creationix/nvm/v{{ nvm_version }}/install.sh"
    dest: "/tmp/nvm_install.sh"
    mode: 0750
  register: nvm_script

- name: Run NVM install script
  command: "/tmp/nvm_install.sh"
  when: nvm_script.changed
